if(!window.criteo_q||window.criteo_q instanceof Array){var oldQueue=window.criteo_q||[];window.criteo_q=function(){function l(a){for(var b=document.cookie.split(";"),e=0;e<b.length;e++){var f=b[e],c=f.substr(0,f.indexOf("=")).replace(/^\s+|\s+$/g,""),f=f.substr(f.indexOf("=")+1);if(c===a)return(decodeURIComponent||unescape)(f)}return null}function I(a,b){if(a&&1<a.length){"?"===a[0]&&(a="&"+a.substr(1));var e="&"+b+"=",f=a.indexOf(e);if(-1!==f){var c=a.indexOf("&",f+e.length);return a.slice(f+e.length,
0>c?void 0:c)}}}var B=[],p=function(a,b){try{return void 0===b?a():a.apply(this,b)}catch(e){B.push(e)}},r=function(a,b){p(function(){if(!("undefined"===typeof window||"function"!==typeof window.setTimeout))return window.setTimeout(a,b)})},C=function(a,b,e,c){p(function(){if(!("undefined"===typeof a||"function"!==typeof a.addEventListener))return a.addEventListener(b,e,c)})},J=function(a,b,e){p(function(){if(!("undefined"===typeof a||"function"!==typeof a.attachEvent))return a.attachEvent(b,e)})},
t=function(a){r(function(){null!==a&&null!==a.parentElement&&a.parentElement.removeChild(a)},3E4)},D=function(){var a=navigator.userAgent.match(/^Mozilla\/5\.0 \([^)]+\) AppleWebKit\/[^ ]+ \(KHTML, like Gecko\) Version\/([^ ]+)( Mobile\/[^ ]+)? Safari\/[^ ]+$/i),b=!!a,a=a&&11<=parseFloat(a[1]);return{is_safari:b,has_itp:a}}(),c={bodyReady:!1,domReady:!1,queue:[],actions:[],disingScheduled:[],accounts:[],acid:null,axid:null,pxsig:null,idcpy:null,idfs:null,idfs_read:!1,sid:null,sid_read:!1,tld:null,
optout:!1,ccp:null,cop:null,ua:D,syncframe_loading:D.is_safari,waiting_syncframe:D.has_itp,is_cbs_enabled:!1},d={tagVersion:"4.6.2",handlerUrlPrefix:("https:"===document.location.protocol?"https://sslwidget.":"http://widget.")+"criteo.com/event",handlerResponseType:"single",responseType:"js",handlerParams:{v:"4.6.2"},extraData:[],customerInfo:[],manualDising:!1,manualFlush:!1,disOnce:!1,partialDis:!1,idfsCookieName:"cto_idfs",guidCookieName:"cto_idcpy",secureIdCookieName:"cto_sid",lwidCookieName:"cto_lwid",
guidCookieRetentionTimeHours:9490,optoutCookieName:"cto_optout",optoutCookieRetentionTimeHours:43800,gumSyncFrameEndPoint:window.CriteoSyncFrameUrlOverride||"https://gum.criteo.com/syncframe",gumSyncFrameId:"criteo-syncframe",forceSyncFrame:!1,eventMap:{applaunched:"al",viewitem:"vp",viewhome:"vh",viewlist:"vl",viewbasket:"vb",viewsearch:"vs",tracktransaction:"vc",calldising:"dis",setdata:"exd",setemail:"ce"},propMap:{event:"e",account:"a",currency:"c",product:"p",item:"p","item.id":"i","item.price":"pr",
"item.quantity":"q","product.id":"i","product.price":"pr","product.quantity":"q",data:"d",keywords:"kw",checkin_date:"din",checkout_date:"dout",deduplication:"dd",attribution:"at","attribution.channel":"ac","attribution.value":"v",user_segment:"si",new_customer:"nc",customer_id:"ci",email:"m",hash_method:"h",transaction_value:"tv",responseType:"rt",page_name:"pn",page_id:"pi",page_number:"pnb",category:"ca",filters:"f","filters.name":"fn","filters.operator":"fo","filters.value":"fv",retailer_visitor_id:"rvi",
price:"pr",availability:"av",sub_event_type:"se",store_id:"s",zipcode:"z"},setters:{seturl:{cfg:"handlerUrlPrefix",evt:"url"},setaccount:{cfg:"account",evt:"account"},setuat:{cfg:"uat",evt:"uat"},setcalltype:{cfg:"handlerResponseType",evt:"type"},setresponsetype:{cfg:"responseType",evt:"type"},setpartnerpayload:{cfg:"partnerPayload",evt:"payload"},oninitialized:{cfg:"onInitialized",evt:"callback"},ondomready:{cfg:"onDOMReady",evt:"callback"},beforeappend:{cfg:"beforeAppend",evt:"callback"},aftereval:{cfg:"afterEval",
evt:"callback"},onflush:{cfg:"onFlush",evt:"callback"}},flags:{disonce:"disOnce",manualdising:"manualDising",manualflush:"manualFlush",nopartialflush:"noPartialFlush",disonpartialflush:"partialDis"}},E=[],u=function(a,b,e){var c=new Date;c.setTime(c.getTime()+36E5*e);e="expires="+c.toUTCString();for(var c=document.location.hostname.split("."),d=null,g=0;g<c.length;++g){var d=c.slice(c.length-g-1,c.length).join("."),k="domain=."+d;document.cookie=a+"="+(encodeURIComponent||escape)(b)+";"+e+";"+k+";path=/";
if((k=l(a))&&k===b)break}return d||document.location};c.tld=function(){var a=u("cto_tld_test","woot",1);u("cto_tld_test","",0);return a}();var P=function(){var a,b=document.createElement("iframe"),e=encodeURIComponent||escape;a=window;var f=!1;try{for(;a.parent.document!==a.document;)if(a.parent.document)a=a.parent;else{f=!0;break}}catch(h){f=!0}var g="";if(f)try{if(g=a.top.location.href,!g)var k=a.location.ancestorOrigins,g=k[k.length-1]}catch(l){g=a.document.referrer}else g=a.location.href;f=g;
k=document.createElement("a");k.href=f;e=e(k.hostname);f={uid:c.idcpy,idfs:c.idfs,optout:c.optout,sid:c.sid,lwid:c.lwid,tld:c.tld,origin:window.SYNCFRAME_ORIGIN||"onetag",version:d.tagVersion.replace(/\./g,"_"),topUrl:e};k=d.gumSyncFrameEndPoint;k="#gum-debug-mode"===window.location.hash?k+("?debug=1&topUrl="+e):k+("?topUrl="+e);k+="#"+JSON.stringify(f);b.src=k;b.id=d.gumSyncFrameId;b.width=0;b.height=0;b.frameBorder=0;b.setAttribute("style","border-width:0px; margin:0px; display:none");t(b);return b},
w=function(a,b,e){u(a,b,e);if(window.localStorage)try{window.localStorage.setItem(a,b)}catch(c){}},x=function(a){var b;window.localStorage&&(b=window.localStorage.getItem(a));return l(a)||b},y=function(a){u(a,"",0);window.localStorage&&window.localStorage.removeItem(a)},Q=function(){var a=(new Date).getTime();"undefined"!==typeof performance&&"function"===typeof performance.now&&(a+=performance.now());return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(b){var e=(a+16*Math.random())%
16|0;a=Math.floor(a/16);return("x"===b?e:e&3|8).toString(16)})},R=function(a){c.waiting_syncframe=c.waiting_syncframe&&!a.idcpy&&!a.sid&&!a.optout&&!a.idfs;c.waiting_syncframe&&r(function(){c.waiting_syncframe&&(c.waiting_syncframe=!1,v())},1E4)},S=function(){if(c.syncframe_loading&&window.addEventListener||d.forceSyncFrame){var a=P(),b=function(a){var b=a.data;if(b.isCriteoMessage){a.stopPropagation();c.syncframe_loading=!1;c.idfs_read=b.idfsRead;if(b.optout)c.optout=!0,w(d.optoutCookieName,"1",
d.optoutCookieRetentionTimeHours),y(d.guidCookieName),y(d.idfsCookieName),y(d.secureIdCookieName);else if(b.uid||b.idfs||b.sid)b.uid&&(a=b.uid,c.idcpy=a,w(d.guidCookieName,a,d.guidCookieRetentionTimeHours)),b.idfs&&(a=b.idfs,c.idfs=a,w(d.idfsCookieName,a,d.guidCookieRetentionTimeHours)),b.removeSid?y(d.secureIdCookieName):b.sid&&(b=b.sid,c.sid=b,c.sid_read=!0,w(d.secureIdCookieName,b,d.guidCookieRetentionTimeHours));c.waiting_syncframe&&c.waiting_syncframe&&(c.waiting_syncframe=!1,v())}};window.addEventListener&&
(C(window,"message",b,!0),c.queue.push({event:"appendtag",element:a}))}else c.syncframe_loading=!1},F=function(a){if(a&&a.referrer){var b=a.createElement("a");b.href=a.referrer;return b}return null};p(function(){c.idcpy=x(d.guidCookieName);c.optout=Boolean(x(d.optoutCookieName));c.idfs=x(d.idfsCookieName);c.sid=x(d.secureIdCookieName);var a=l(d.lwidCookieName);a||(u(d.lwidCookieName,Q(),d.guidCookieRetentionTimeHours),a=l(d.lwidCookieName));c.lwid=a||"NA";var a=l("criteo_acid"),b=l("cto_axid"),e=
l("cto_pxsig"),f=l("cto_optout");null===a&&null===b&&null===f&&null===e?(a=new Date,a.setTime(a.getTime()+1E4),a="expires="+a.toUTCString(),document.cookie=["criteo_write_test=ChUIBBINbXlHb29nbGVSdGJJZBgBIAE","path=/",a].join("; "),a=l("criteo_write_test"),c.canWriteCookie=null!==a,document.cookie="criteo_write_test=; path=/; expires=Thu, 01 Jan 1970 00:00:00 UTC"):(c.acid=a,c.axid=null!==f?"optout":b,c.pxsig=e,c.canWriteCookie=!0);var a=window,h,g;try{g=a.top.location.search}catch(k){b=a;try{for(;b.parent.document!==
b.document;)if(b.parent.document)b=b.parent;else break}catch(n){}if(b&&(b=F(b.document)))g=b.search}g&&(h=I(g,"cto_pld"));if(!h)try{var m=F(a.top.document);m&&m.search&&(h=I(m.search,"cto_pld"))}catch(p){}h&&(c.cop=h);R(c)});p(function(){var a=l("criteo_cookie_perm");null!==a&&(c.ccp=a)});var U=function(a){(function e(){document.body?r(a,0):r(e,10)})()},z=function(a){return"undefined"===typeof a||""===a},G=function(a,b){c.is_cbs_enabled&&z(a.page_id)&&(a.page_id=b)},V=function(a,b){if("complete"===
a.readyState)b();else if(a.addEventListener)C(a,"DOMContentLoaded",b,!1),C(window,"load",b,!1);else{J(a,"onreadystatechange",b);J(window,"onload",b);var e=!1;try{e=null===window.frameElement&&document.documentElement}catch(c){}if(e&&e.doScroll)(function T(){if(e){try{e.doScroll("left")}catch(a){return r(T,50)}b()}})();else{var d=!1,g=a.onload,k=a.onreadystatechange;a.onload=a.onreadystatechange=function(){k instanceof Function&&k();if(!d&&(!a.readyState||"loaded"===a.readyState||"complete"===a.readyState))g instanceof
Function&&g(),d=!0,b()}}}},K=function(){p(function(){var a=null,b="undefined"!==typeof performance&&"function"===typeof performance.now;b&&(a=performance.now());for(var e=0;e<arguments.length;++e)c.queue.push(arguments[e]);v();e=!1;if(200<d.extraData.length)e=!0;else for(var f=0;f<d.extraData.length;++f){var h=d.extraData[f],g=0;if(Object.keys)g=Object.keys(h).length;else for(var k in h)Object.prototype.hasOwnProperty.call(h,k)&&(g+=1);if(200<g){e=!0;break}}e&&(d.extraData=[]);d.customerInfo=[];c.is_cbs_enabled=
!1;b&&(a=performance.now()-a,E.pushTime=a)},arguments)},v=function(){for(var a=[],b=c.queue,e=0;e<b.length;++e){var f=b[e];if(f instanceof Array)b.splice.apply(b,[e+1,0].concat(f));else if(f instanceof Function)b.splice(e+1,0,f());else if(f&&"[object Object]"===f.toString())switch(q(f,e,b,a)){case 0:a.push(f);break;case -1:a=a.concat(b.slice(e)),e=b.length}}d.afterEval instanceof Function&&(a=d.afterEval(b,a,c,d));c.queue=a||[];!d.manualFlush&&((!d.noPartialFlush||0===c.queue.length)&&!c.waiting_syncframe)&&
L(0!==c.queue.length)},q=function(a,b,e,f){if(!c.domReady&&a.requiresDOM&&"no"!==a.requiresDOM)return"blocking"===a.requiresDOM?-1:0;delete a.requiresDOM;if(!a.event)return n(a),1;a.account&&H(a.account,c.accounts);var h=a.event;a.event=a.event.toLowerCase();switch(a.event){case "setdata":return a=n(a),M(a),N(c.actions,n(a)),1;case "setparameter":for(var g in a)"event"!==g.toLowerCase()&&a.hasOwnProperty(g)&&(d.handlerParams[g]=a[g]);return 1;case "calldising":a.hasOwnProperty("account")||(a.account=
c.accounts);b=d.handlerResponseType;a.hasOwnProperty("type")&&(b=a.type,delete a.type);H(a.account,c.disingScheduled);"sequential"===b&&(a.dc=!0);break;case "setzipcode":case "setstore":return a.event="setdata",q(a);case "setcustomerid":return a.event="setdata",a.customer_id=a.id,delete a.id,q(a);case "setretailervisitorid":return c.is_cbs_enabled=!0,a.event="setdata",a.retailer_visitor_id=a.id,delete a.id,q(a);case "setemail":case "sethashedemail":case "ceh":a.event="setemail";if(a.hasOwnProperty("email")){a.email instanceof
Array||(a.email=[a.email]);b=a.email;e=[];for(f=0;f<b.length;f++)void 0!==b[f]&&null!==b[f]&&e.push(String(b[f]));a.email=e}b=n(a);d.customerInfo.push(b);O(c.actions,n(a));return 1;case "setsitetype":b="d";if("mobile"===a.type||"m"===a.type)b="m";if("tablet"===a.type||"t"===a.type)b="t";a.event="setdata";delete a.type;a.site_type=b;return q(a);case "appendtag":if(c.bodyReady&&(!d.container||!document.body.contains(d.container)))(b=document.body)?(e=document.createElement("div"),e.setAttribute("id",
"criteo-tags-div"),e.style.display="none",b.appendChild(e),b=e):b=void 0,d.container=b;a.url&&(a.isImgUrl?(b=document.createElement("img"),b.setAttribute("style","display:none;"),b.setAttribute("width","1"),b.setAttribute("height","1")):(b=document.createElement("script"),b.setAttribute("async","true"),b.setAttribute("type","text/javascript")),b.setAttribute("src",a.url),a.element=b);d.beforeAppend instanceof Function&&(a.element=d.beforeAppend(a.element,c,d));n(a);if(a.element&&(a.element.tagName||
a.isImgUrl))if(!d.container&&("script"===a.element.tagName.toLowerCase()||a.isImgUrl))b=document.getElementsByTagName("script")[0],a.element.setAttribute("data-owner","criteo-tag"),b.parentNode.insertBefore(a.element,b),t(a.element);else if(d.container)d.container.appendChild(a.element),t(a.element);else return 0;return 1;case "gettagstate":return a.callback instanceof Function?a.callback(c,d):1;case "viewsearchresult":case "viewcategory":G(a,h);a.event="viewlist";break;case "viewlist":c.is_cbs_enabled&&
z(a.page_id)&&(z(a.category)?z(a.keywords)?a.page_id="viewList":a.page_id="viewSearchResult":a.page_id="viewCategory");break;case "viewitem":case "viewhome":case "viewbasket":case "tracktransaction":G(a,h);break;case "viewstore":G(a,h);a.event="viewHome";a.sub_event_type="s";break;case "flush":case "flushevents":return L(b!==e.length-1||0!==f.length),1}if(b=d.setters[a.event])return d[b.cfg]=a[b.evt],1;if(b=d.flags[a.event])return d[b]=!0,1;c.actions.push(n(a));return 1},L=function(a){d.onFlush instanceof
Function&&(c.actions=d.onFlush(c.actions,c,d));if(0!==c.actions.length){for(var b=0;b<d.extraData.length;++b)N(c.actions,d.extraData[b]);for(b=0;b<d.customerInfo.length;++b)O(c.actions,d.customerInfo[b]);if(!d.manualDising&&(!a||d.partialDis)){a=[];for(b=0;b<c.accounts.length;++b)A(c.disingScheduled,c.accounts[b])||a.push(c.accounts[b]);0<a.length&&q({event:"callDising",account:a})}a=c.actions;b=[];1===c.accounts.length&&(d.account=c.accounts[0]);d.account&&b.push("a="+m(d.account,[]));"js"!==d.responseType&&
b.push("rt="+m(d.responseType,[]));if(d.handlerParams){var e=decodeURIComponent(m(d.handlerParams,[]));e&&b.push(e)}d.uat&&c.is_cbs_enabled&&b.push("uat="+(encodeURIComponent||escape)(d.uat));for(e=0;e<a.length;++e)a[e].account&&s(d.account,a[e].account)&&delete a[e].account,b.push("p"+e+"="+m(a[e],[]));null!==c.acid&&b.push("acid="+c.acid);null!==c.axid&&b.push("axid="+c.axid);null!==c.pxsig&&b.push("pxsig="+c.pxsig);c.canWriteCookie&&b.push("adce=1");null!==c.ccp&&b.push("ccp="+c.ccp);null!==c.cop&&
b.push("cop="+c.cop);c.idcpy&&(b.push("idcpy="+c.idcpy),b.push("iddom="+document.location.hostname));c.idfs&&b.push("idfs="+c.idfs);c.idfs_read&&b.push("idfs_read=1");c.optout&&b.push("optout=1");c.sid&&(b.push("sid="+c.sid),b.push("sid_read="+(c.sid_read?"1":"0")));c.lwid&&b.push("lwid="+c.lwid);c.tld&&b.push("tld="+c.tld);l("cto_clc")&&b.push("clc=1");d.partnerPayload&&b.push("pp="+m(d.partnerPayload,[]));b.push("dtycbr="+Math.floor(1E5*Math.random()));a=b.join("&");a={event:"appendTag",url:d.handlerUrlPrefix+
"?"+a,isImgUrl:"gif"===d.responseType};c.actions=[];q(a);d.disOnce||(c.disingScheduled=[])}},M=function(a){for(var b=0;b<d.extraData.length;++b){var e=d.extraData[b];if(e.event===a.event&&("undefined"===typeof a.account&&"undefined"===typeof e.account||s(a.account,e.account))){for(var c in a)"account"!==c&&(e[c]=a[c]);return}}d.extraData.push(a)},N=function(a,b){for(var e=0;e<a.length;++e){var c=a[e];if(c.event===b.event&&s(b.account,c.account)){for(var d in b)b.hasOwnProperty(d)&&"account"!==d&&
(c[d]=b[d]);return}}a.push(b)},O=function(a,b){for(var e=0;e<a.length;++e){var c=a[e];if(c.event===b.event&&s(b.account,c.account)&&("hash_method"in b?b.hash_method:"")===("hash_method"in c?c.hash_method:"")){if(b.hasOwnProperty("email")){for(var e=c,c=c.email,d=b.email,g=[],k=0;k<d.length;++k)A(c,d[k])||g.push(d[k]);c=c.concat(g);e.email=c}return}}a.push(b)},n=function(a){var b=a;if(a instanceof Function)return b=a(),b instanceof Function?b:n(b);if(a instanceof Array)for(var b=[],c=0;c<a.length;++c)b[c]=
n(a[c]);else if(a&&"[object Object]"===a.toString())for(c in b={},a)a.hasOwnProperty(c)&&(b[c]=n(a[c]));return b},W=function(a,b){var c=b.join(".");return d.propMap[c]?d.propMap[c]:a},s=function(a,b){if(!(a instanceof Array))return s([a],b);if(!(b instanceof Array))return s(a,[b]);if(a.length!==b.length)return!1;for(var c=0;c<a.length;++c)if(!A(b,a[c]))return!1;return!0},m=function(a,b){var c="";if(a instanceof Function)c=m(a(),b);else if(a instanceof Array){for(var f=[],h=0;h<a.length;++h)f[h]=m(a[h],
b);c+="["+f.join(",")+"]"}else if(a&&"[object Object]"===a.toString()){f=[];for(h in a)if(a.hasOwnProperty(h)){var g=b.concat([h]);f.push(W(h,g)+"="+m(a[h],g))}c+=f.join("&")}else c=1===b.length&&"event"===b[0]?c+(d.eventMap[a.toLowerCase()]?d.eventMap[a.toLowerCase()]:a):c+a;return(encodeURIComponent||escape)(c)},H=function(a,b){if(a instanceof Array)for(var c=0;c<a.length;++c)H(a[c],b);else A(b,a)||b.push(a)},A=function(a,b){for(var c=JSON.stringify||encodeURIComponent||escape,d=c(b),h=0;h<a.length;++h)if(a[h]===
b||c(a[h])===d)return!0;return!1},X=function(a){try{var b=F(a);b&&b.hostname!==a.location.hostname&&M({event:"setData",ref:b.protocol+"//"+b.hostname})}catch(c){}},Y=function(a,b){if(a&&b){var c=/^\#(enable|disable)-criteo-tag-debug-mode(\=(\d+))?$/.exec(b);if(c&&4==c.length){var d="enable"==c[1],h=c[3],c="criteoTagDebugMode=";d&&(h&&!isNaN(h))&&(c+=parseInt(h,10));d=d?(new Date).getTime()+864E5:0;d="expires="+(new Date(d)).toUTCString();document.cookie=[c,"path=/",d].join("; ");window.location.href=
window.location.href.substr(0,window.location.href.indexOf("#"))}}},Z=function(a){if(a){var b=a.createElement("script");b.setAttribute("type","text/javascript");b.setAttribute("src",a.location.protocol+"//static.criteo.net/js/ld/ld-tag-debug.4.6.2.js");a=a.getElementsByTagName("script")[0];a.parentNode.insertBefore(b,a)}};return p(function(){U(function(){c.bodyReady=d.onInitialized instanceof Function?d.onInitialized(c,d):!0;S();v()});V(document,function(){c.domReady=d.onDOMReady instanceof Function?
d.onDOMReady(c,d):!0;v()});X(document);Y(document,window.location.hash);var a;a=document?"function"!=typeof Array.prototype.indexOf?!1:-1!==document.cookie.indexOf("criteoTagDebugMode="):!1;if(a){var b={originalPush:K,stagedPushes:[],stagedErrors:[],m_state:c,m_config:d,setProtectedTimeout:r,removeLater:t,performances:E,exceptions:B,push:function(){0<arguments.length&&this.stagedPushes.push(arguments)},pushError:function(a){this.stagedErrors.push(a)}};window.onerror=function(a){return function(c,
d,g,k){b.pushError({message:c,url:d,lineNumber:g,column:k});return a&&"function"===typeof a?a.apply(this,arguments):!1}}(window.onerror);Z(document);return b}return{push:K,removeLater:t,performances:E,exceptions:B}})}();window.criteo_q.push.apply(window.criteo_q,oldQueue)};
