//tealium universal tag - utag.95 ut4.0.201804250212, Copyright 2018 Tealium.com Inc. All Rights Reserved.
function sRAN(){var t=DataLayer&&DataLayer.Sale&&DataLayer.Sale.Basket?DataLayer.Sale.Basket:{},e=t.affiliateMID||t.ranMID;if(!e)return!1;var a=t.allowCommission;if(a&&typeof(a)==="string"&&"false"==a.toLowerCase())return!1;for(var r=t.orderid||"OrderNumberNotAvailable",i="",n="",o="",s="",u=t.currency||"",m=(t.taxAmount&&Math.abs(Math.round(100*Number(t.taxAmount))),t.discountAmount&&Math.abs(Math.round(100*Number(t.discountAmount))),t.customerStatus,document.location.protocol+"//track.linksynergy.com/eventnvppixel?"),l=[],c=0;c<(t.lineitems?t.lineitems.length:0);c++){for(var d=!1,N=window.JSON?JSON.parse(JSON.stringify(t.lineitems[c])):t.lineitems[c],y=0;y<l.length;y++)l[y].SKU===N.SKU&&(d=!0,l[y].quantity=Number(l[y].quantity)+Number(N.quantity));d||l.push(N)}for(c=0;c<l.length;c++){var N=l[c],b=encodeURIComponent(N.SKU),h=N.unitPriceLessTax||N.unitPrice,p=N.quantity,f=encodeURIComponent(N.productName)||"";i+=b+"|",n+=p+"|",o+=Math.round(100*Number(h))+"|",s+=f+"|"}m+="mid="+e+"&ord="+r+"&skulist="+(i=i.slice(0,-1))+"&qlist="+(n=n.slice(0,-1))+"&amtlist="+(o=o.slice(0,-1))+"&cur="+u+"&namelist="+(s=s.slice(0,-1))+"&img=1";var g,S=document.createElement("img");S.setAttribute("src",m),S.setAttribute("height","1px"),S.setAttribute("width","1px"),(g=document.getElementsByTagName("script")[0]).parentNode.insertBefore(S,g)};try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
if(utag.ut.loader===undefined){u.loader=function(o){var b,c,l,a=document;if(o.type==="iframe"){b=a.createElement("iframe");o.attrs=o.attrs||{"height":"1","width":"1","style":"display:none"};for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}
b.setAttribute("src",o.src);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";for(l in utag.loader.GV(o.attrs)){b[l]=o.attrs[l];}
b.src=o.src;}
if(o.id){b.id=o.id;}
if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){this.onreadystatechange=null;o.cb();}};}}
l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
if(utag.ut.typeOf===undefined){u.typeOf=function(e){return({}).toString.call(e).match(/\s([a-zA-Z]+)/)[1].toLowerCase();};}else{u.typeOf=utag.ut.typeOf;}
u.ev={"view":1};u.map={"product_sub_total":"product_unit_price","product_upc":"product_id"};u.extend=[function(a,b){try{if(1){b['rakuten_tracking_key']='112046'}}catch(e){utag.DB(e)}},function(a,b){try{if(1){b['rakuten_ranMID']='3184'}}catch(e){utag.DB(e)}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f;var TK="";var DD=document.domain;if(DD.indexOf("fds.com")>-1){TK="114515";}
else if(DD.indexOf("macys.com")>-1||DD.indexOf("macysbackstage.com")>-1){TK="112046";}
u.data={"ranMID":"3184","qsp_delim":"&","kvp_delim":"=","base_url":"//intljs.rmtag.com/"+TK+".ct.js","allowCommission":true,"lineitems":[],"item":{},"product_id":[],"product_name":[],"product_quantity":[],"product_unit_price":[],"product_discount":[]};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};c=[];for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
u.data.order_id=u.data.order_id||b._corder||"";u.data.order_subtotal=u.data.order_subtotal||b._csubtotal||"";u.data.order_tax=u.data.order_tax||b._ctax||"";u.data.order_currency=u.data.order_currency||b._ccurrency||"";u.data.order_coupon_code=u.data.order_coupon_code||b._cpromo||"";u.data.customer_id=u.data.customer_id||b._ccustid||"";if(u.data.product_id.length===0&&b._cprod!==undefined){u.data.product_id=b._cprod.slice(0);}
if(u.data.product_name.length===0&&b._cprodname!==undefined){u.data.product_name=b._cprodname.slice(0);}
if(u.data.product_quantity.length===0&&b._cquan!==undefined){u.data.product_quantity=b._cquan.slice(0);}
if(u.data.product_unit_price.length===0&&b.product_sub_total!==undefined){u.data.product_unit_price=b.product_sub_total.slice(0);}
if(u.data.product_discount.length===0&&b._cpdisc!==undefined){u.data.product_discount=b._cpdisc.slice(0);}
window.DataLayer||(window.DataLayer={}),DataLayer.events||(DataLayer.events={});window.DataLayer.events.SiteSection=u.data.siteSection||"1";if(!u.data.order_id){u.loader({"type":"script","src":u.data.base_url,"cb":null,"loc":"script","id":'utag_95'});}
if(!!u.data.order_id){g={};g.orderid=u.data.order_id;g.ranMID=u.data.ranMID||"";g.currency=u.data.order_currency||"";g.customerStatus=u.data.customerStatus||"";g.conversionType=u.data.conversionType||"Sale";g.customerID=u.data.customer_id||"";g.discountCode=u.data.order_coupon_code||"";g.discountAmount=0;if(u.data.order_tax){g.taxAmount=u.data.order_tax;}
g.allowCommission=u.data.allowCommission;if(u.data.product_id.length>0){g.lineitems=[];}
for(var i=0;i<u.data.product_id.length;i++){u.data.item={};u.data.item.quantity=u.data.product_quantity[i];if(u.data.product_unit_price[i]){u.data.item.unitPriceLessTax=u.data.product_unit_price[i];u.data.item.unitPrice=u.data.product_unit_price[i]/u.data.product_quantity[i];}
u.data.item.SKU=u.data.product_id[i];u.data.item.productName=u.data.product_name[i];g.lineitems.push(u.data.item);}
window.rm_trans=g;if(!window.DataLayer){window.DataLayer={Sale:{Basket:rm_trans}};}else{DataLayer.Sale=DataLayer.Sale||{Basket:rm_trans};DataLayer.Sale.Basket=DataLayer.Sale.Basket||rm_trans;}
DataLayer.Sale.Basket.Ready=true;sRAN();}
}};utag.o[loader].loader.LOAD(id);}("95","macys.main"));}catch(error){utag.DB(error);}
