//tealium universal tag - utag.536 ut4.0.201804250212, Copyright 2018 Tealium.com Inc. All Rights Reserved.
window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)};gtag('js',new Date());try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={"page_type":"pagetype","product_id":"product_id","product_category_id":"product_category"};u.extend=[];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={"a":a,"conversion_id":"AW-1012760282","conversion_label":"","base_url":"https://www.googletagmanager.com/gtag/js?id=AW-1012760282","product_id":[],"event_name":'',"product_unit_price":[],"product_quantity":[],"pagetype":"",'search_term':'','product_category':'','order_subtotal':""};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
u.data.order_id=u.data.order_id||b._corder||"";u.data.order_subtotal=u.data.order_subtotal||b._csubtotal||"";u.data.order_currency=u.data.order_currency||b._ccurrency||"USD";u.data.product_id=u.data.product_id||b._cprod||[];u.data.product_quantity=u.data.product_quantity||b._cquan||[];if(u.data.product_unit_price.length===0&&b._cprice!==undefined){u.data.product_unit_price=b._cprice.slice(0);}
u.loader_cb=function(){utag.DB("send:536:CALLBACK");u.initialized=true;var gParameters={};gParameters.send_to=u.data.conversion_id||'';if(u.data['a']=='view'){u.data.event_name="page_view";}
if(u.data['pagetype']=="home page"){gParameters['ecomm_pagetype']='home';}else if(u.data["pagetype"]=="product"){gParameters.ecomm_pagetype='product';if(utag.ut.typeOf(u.data.product_id)=="string"){gParameters['ecomm_prodid']=u.data.product_id;}else if(utag.ut.typeOf(u.data.product_id)=="array"){gParameters['ecomm_prodid']=u.data.product_id[0];}
if(u.data.product_unit_price.length>0){gParameters['ecomm_totalvalue']=u.data.product_unit_price[0];}
if(u.data.product_category.length>0){gParameters['ecomm_category']=u.data.product_category;}}else if(u.data['pagetype']=="browse"||u.data['pagetype']=="splash"){gParameters.ecomm_pagetype='category';}else if(u.data['pagetype']=="search results"){gParameters.ecomm_pagetype='searchresults';if(b['top_6_products']){gParameters.ecomm_prodid=b['top_6_products']}}else if(u.data["pagetype"]=="shopping bag"){gParameters.ecomm_pagetype='cart';if(u.data.product_id.length>0){gParameters.ecomm_prodid=u.data.product_id;gParameters.ecomm_category=u.data.product_category;gParameters.ecomm_quantity=u.data.product_quantity;gParameters.ecomm_totalvalue=u.data.order_subtotal;}}else if(u.data['pagetype']!=''){gParameters['ecomm_pagetype']=u.data['pagetype'];}else{gParameters['ecomm_pagetype']='other';}
if(u.data.order_id){gParameters.send_to=u.data.conversion_id;gParameters.currency=u.data.order_currency;gParameters.transaction_id=u.data.order_id;gParameters.ecomm_totalvalue=u.data.order_subtotal;if(u.data.product_id.length>0){gParameters.ecomm_prodid=u.data.product_id;gParameters.ecomm_category=u.data.product_category;gParameters.ecomm_quantity=u.data.product_quantity;}
gParameters.ecomm_pagetype='purchase';gtag('event','conversion',gParameters);}
if(u.data.event_name){gtag('event',u.data.event_name,gParameters);}
utag.DB("send:536:CALLBACK:COMPLETE");};if(!u.initialized){u.loader({"type":"script","src":u.data.base_url,"cb":u.loader_cb,"loc":"script","id":'utag_176'});gtag('config',u.data['conversion_id']);}else{u.loader_cb();}
}};utag.o[loader].loader.LOAD(id);})("536","macys.main");}catch(error){utag.DB(error);}
